#!/usr/bin/python

# again this is scratchwork to help promote my understanding of music
# these values generated by this program are easily found on the internet
# but I will be deriving them starting from A = 440 Hz because I find value
# from understanding this process from the ground up

# this program will generate valid notes from 20 Hz to 40 kHz

# start with the 12 valid notes using 12-TET 
start = 'A'

chromatic_sharps = []

for i in range(7):
    chromatic_sharps.append(chr(ord(start)+i))
    chromatic_sharps.append(chr(ord(start)+i)+'#')

chromatic_sharps.remove('B#')
chromatic_sharps.remove('E#')


chromatic_flats = []

for i in range(7):
    chromatic_flats.append(chr(ord(start)+i)+'b')
    chromatic_flats.append(chr(ord(start)+i))

chromatic_flats.remove('Cb')
chromatic_flats.remove('Fb')

chromatic_flats.append(chromatic_flats.pop(0))

print(chromatic_flats)
print(chromatic_sharps)

tuning_system = 2.0 ** (1.0/12.0)

notes_hz_sharps = {}
notes_hz_flats = {}

a440 = 440.0

for sharp, flat, i in zip(chromatic_sharps, chromatic_flats, range(len(chromatic_sharps))):
    hz = a440 * (tuning_system ** i)
    notes_hz_sharps[sharp] = hz
    notes_hz_flats[flat] = hz


print(notes_hz_sharps)
print(notes_hz_flats)
    
    
    
    


# ID the note closest to 20 Hz by using 1/2 freq octave rule
# for each of the 12 valid notes

# use double octave rule to generate freq until 40kHz while identifying them


